In [5]:
!pip install numpy
import numpy as np

In [6]:
vector=np.array(range(3,26))
vector

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25])

In [7]:
arreglo=np.array([0,1,2,3,4,0,1,2,3,4])

In [8]:
arreglo

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [9]:
arreglo.sort()

In [10]:
arreglo

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])