## Instalar librerías a utilizar en este archivo

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
lista=[1,2,3]
type(lista)

list

In [4]:
#Crear una matriz a partir de una lista
matriz=numpy.array(lista)
type(matriz)

numpy.ndarray

In [5]:
matriz

array([1, 2, 3])

In [6]:
import numpy as np
matriz2=np.array(lista)
matriz2

array([1, 2, 3])

In [7]:
matriz.ndim #Para saber cuántas dimensiones tiene la matriz

1

In [8]:
matriz.shape #Para saber cuántos elementos tiene la matriz

(3,)

In [9]:
lista3=[1.0,True,"a",3]

In [10]:
matriz3=np.array(lista3)
matriz3

array(['1.0', 'True', 'a', '3'], dtype='<U32')

In [11]:
#Todos los elementos pasaron a ser de un solo tipo, en este caso se convirtieron en string

In [12]:
print(matriz3.dtype)

<U32


In [13]:
print(matriz2.dtype)

int32


In [14]:
#Las matrices solo pueden tener un tipo de dato

In [15]:
matriz4=np.array([1,2,3], dtype="float") #crear una matriz a partir de escribirla dentro de la instrucción (escribir dentro de np.array)

In [16]:
matriz4

array([1., 2., 3.])

In [17]:
matriz4.dtype

dtype('float64')

In [18]:
matriz5=np.array([1,2,3], dtype="float16")
matriz5.dtype

dtype('float16')

In [ ]:
#Operaciones con matrices

In [19]:
m=[1,2,3]
n=[3,4,5]

In [20]:
m+n #Al sumar dos listas las coloca una detrás de otra

[1, 2, 3, 3, 4, 5]

In [21]:
matriz_m=np.array(m)
matriz_n=np.array(n)
matriz_m+matriz_n

array([4, 6, 8])

In [22]:
#Matriz tiene índices [a,b,c]. las matrices deben de tener el mismo número de elementos

In [23]:
np.square(matriz_m)

array([1, 4, 9], dtype=int32)

In [24]:
matriz_m[0]

1

In [25]:
matriz_m[-1]

3

In [26]:
matriz_m[-3]

1

In [27]:
#Se pueden editar los elementos de una matriz, de manera similar a las listas
matriz_m[0] = True

In [28]:
matriz_m

array([1, 2, 3])

In [29]:
matriz_m[1] = True

In [30]:
matriz_m

array([1, 1, 3])

In [31]:
desordenada=np.array([5,21,8,2,77,38,-90])
desordenada.sort()
desordenada

array([-90,   2,   5,   8,  21,  38,  77])

In [32]:
matriz_1=np.array(range(1,6))
matriz_2=np.array(range(4,11))

In [33]:
matriz_1

array([1, 2, 3, 4, 5])

In [34]:
matriz_2

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
matriz_3=np.append(matriz_1,matriz_2, axis=0) #da lo mismo si no pusiera axis porque por defecto ya está en el eje 0

In [38]:
matriz_3

array([ 1,  2,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.insert(matriz_3,2,11)

array([ 1,  2, 11,  3,  4,  5,  4,  5,  6,  7,  8,  9, 10])

# Lunes

In [40]:
# Matrices bidimensionales
bidim=np.array([[18,23,20],[400,380,710]])
bidim

array([[ 18,  23,  20],
       [400, 380, 710]])

In [41]:
bidim.shape #Dimensiones de la  matriz

(2, 3)

In [42]:
bidim.ndim #Cuántas n dimensiones posee?

2

In [43]:
bidim[-1,-1]

710

In [44]:
bidim[0,0]

18

In [45]:
np.resize(bidim,(10,10))

array([[ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400],
       [380, 710,  18,  23,  20, 400, 380, 710,  18,  23],
       [ 20, 400, 380, 710,  18,  23,  20, 400, 380, 710],
       [ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400],
       [380, 710,  18,  23,  20, 400, 380, 710,  18,  23],
       [ 20, 400, 380, 710,  18,  23,  20, 400, 380, 710],
       [ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400],
       [380, 710,  18,  23,  20, 400, 380, 710,  18,  23],
       [ 20, 400, 380, 710,  18,  23,  20, 400, 380, 710],
       [ 18,  23,  20, 400, 380, 710,  18,  23,  20, 400]])

In [47]:
f=np.arange(1,16,7) #Matriz desde a(1) hasta b-1(16-1=15) con un salto de 7
f

array([ 1,  8, 15])

In [48]:
g=np.arange(1,10) #Matriz de a hasta b-1
g

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
gg=np.array([g,g])
gg

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [50]:
h=np.reshape(np.array(range(1,26)),(5,5))
h

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
i=np.asarray([1,2,3])
i

array([1, 2, 3])

In [52]:
i.dtype

dtype('int32')

In [54]:
j=i.astype("complex64") #cambiar tipo de datos a complex

In [55]:
j.dtype

dtype('complex64')

In [56]:
j

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)

In [57]:
k=i.astype("float64") #cambiar a float

In [58]:
k

array([1., 2., 3.])

In [59]:
k.dtype

dtype('float64')

In [60]:
np.eye(2, dtype=int) #estas matrices tienen un 1 en la diagonal principal

array([[1, 0],
       [0, 1]])

In [61]:
np.eye(10, dtype=int) #se especifica un solo número porque es una matriz cuadrada

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [62]:
np.eye(2,3) #por defecto la matriz tiene decimales

array([[1., 0., 0.],
       [0., 1., 0.]])

In [63]:
np.eye(2,3, k=1) #k sirve para desplazar k lugares

array([[0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(10,7,k=3,dtype=int)

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [65]:
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C',]*,like=None)

In [67]:
np.eye(N=10,M=7,k=3)

array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [68]:
np.eye(N=7,M=10,k=3) #volteada

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [69]:
np.zeros(3) #matriz de ceros

array([0., 0., 0.])

In [70]:
np.ones(shape=(2,3)) #matriz de unos

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
np.empty(shape=(3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.91294425e-321],
       [1.12890176e-311, 1.12890176e-311, 0.00000000e+000]])

In [72]:
np.full(shape=(2,8), fill_value=False)

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [73]:
np.identity(4) #siempre 1s en diagonal principal y siempre cuadradas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
##Operacdores y Operaciones

In [76]:
i=4
i**4

256

In [77]:
i*=10 #multiplica el valor almacenado en i por el escrito a la derecha del igual

In [78]:
i

40

In [79]:
i/=10 #puede alterar el tipo de variable
i

4.0

In [80]:
i -=1 #mantiene el tipo e variable

In [84]:
i

4.0

In [82]:
i +=10 #mantiene el tipo de variable
i

13.0

In [83]:
i //=3
i

4.0

In [85]:
i%=3
i

1.0

In [87]:
contador=1
contador = contador + 1
contador

2

In [88]:
contador +=1
contador

3